# Generated by Django 5.0.1 on 2024-01-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
