# Generated by Django 5.0.1 on 2024-01-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esite', '0004_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
