# Generated by Django 5.0.1 on 2024-01-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esite', '0005_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='expyear',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='zipcode',
        ),
    ]
