# Generated by Django 5.0.1 on 2024-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esite', '0006_remove_shipping_cvv_remove_shipping_expyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
