# Generated by Django 5.0.1 on 2024-01-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esite', '0007_contact_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
